In [ ]:
# Q1 Array Creation and Manipulation
import numpy as np
# i) Create different types of arrays (1D, 2D, 3D) using various methods (np.array, np.arange, np.linspace, etc.).
# using np.array
arr_1D = np.array(10)
print(arr_1D)

list1 = [1,2,3,5,6]
list2 = [5,7,8,3,2]
list3 = [4,7,9,3,9]

arr_2D = np.array([list1 , list2])
print(arr_2D)
arr_3D = np.array([list1, list2, list3])
print(arr_3D)

# using np.arange
arr = np.arange(15)
print(arr)

#using linspace
array = np.linspace(0 , 10, 11)
print(array)


10
[[1 2 3 5 6]
 [5 7 8 3 2]]
[[1 2 3 5 6]
 [5 7 8 3 2]
 [4 7 9 3 9]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
# ii) Perform basic operations on arrays (indexing, slicing, reshaping, concatenation).

# Indexing
arr = np.array([1,3,4,5,7,8])
print(arr)
print(arr[3])

# Slicing
print(arr[2:4])
print(arr[::-1])

# Reshaping
arr2 = np.arange(10).reshape(2,5)
print(arr2)

#Concatenation
array1 =  np.array([1,2,3,4,5])
array2 = np.array([6,7,8,9,10])

updated_array = np.concatenate((array1 , array2))
print(updated_array)


[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# iii) Investigate array attributes like shape, size, dtype, ndim.

# Shape
arr = np.array([[1,2,3,4] , [5,6,7,8] , [3,6,9,2]])
print(arr.shape)

# Size
print(arr.size)

# dtype
print(arr.dtype)

# ndim
print(arr.ndim)

[[1 2 3 4]
 [5 6 7 8]
 [3 6 9 2]]
(3, 4)
12
int64
2


In [ ]:
# iv) Use methods like reshape, resize, flatten

# Reshape
arr = np.arange(8)
print(arr)

new_array = arr.reshape(4,2)
print(new_array)

new_array2 = arr.reshape(2,4)
print(new_array2)

# Resize
# arr.resize(5,2)
# print(arr)

# Flatten
arr.flatten()
print(arr)


[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3 4 5 6 7]


In [ ]:
# Q2 Data Loading and Preprocessing

# i) Load a dataset (e.g., CSV, Excel) using NumPy.

file_path = '/content/drive/My Drive/data.csv'
data = np.genfromtxt( file_path , delimiter = "," , skip_header = 1)


In [ ]:
# ii)	Clean and preprocess the data (handling missing values, normalization, standardization).

normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print("Normalized Data : \n" , normalized_data)

mean = np.mean(data)
standard_deviation = np.std(data)
standardized_data = (data - mean)/ standard_deviation
print("Standardized Data : \n" , standard_deviation)

Normalized Data : 
 [0.08522727 0.76704545 0.89204545 0.51136364 0.53409091 0.65909091
 0.1875     0.18181818 0.46590909 0.57386364 0.91477273 0.96590909
 0.         0.32386364 0.21590909 0.22727273 0.42045455 0.14204545
 0.65340909 0.76704545 1.         0.44318182 0.89204545 0.85795455
 0.38636364 0.80113636 0.5        0.19318182 0.72727273]
Standardized Data : 
 51.120803046917324


In [ ]:
# iii) Calculate mean, median, standard deviation, variance, and other statistical measures.

# Mean
mean_value = np.mean(data)
print('Mean : ' ,  mean_value)

# Median
median_value = np.median(data)
print("Median : " , median_value)

# Standard Deviation
standard_deviation = np.std(data)
print("Standard Deviation" , standard_deviation)

# Variance
variance_value = np.var(data)
print("Variance : ", variance_value)


Mean :  107.79310344827586
Median :  105.0
Standard Deviation 51.120803046917324
Variance :  2613.3365041617117
